Multiple mentioning issue fixed in chat
KoffeeMakerz/vue-advanced-chat pull request #20
Opened 2024-11-27 10:52 UTC by SachinL98

When multiple times mentioned a same user in the chat, all occurrences must be displayed as name.

2024-11-27 11:20 UTC, gihansdp requested changes
Since the linked ticket is from saas project, update the saas project to install the `vue-advanced-chat` from this branch using and another PR. Then we can test this change on saas project.

2024-11-28 06:56 UTC, gihansdp commented
You need to build this for changes to take effect as a library. Run `npm run build` on root folder.

2024-11-28 07:06 UTC, SachinL98 commented
Done

2024-11-28 07:08 UTC, gihansdp commented on package.json
> +		"vue-advanced-chat": "^2.1.0",
What's this? `vue-advanced-chat` require `vue-advanced-chat`?

2024-11-28 07:10 UTC, gihansdp commented on demo/src/firestore/index.js
> +const config = {
Do not commit your keys. Keep it as it is to get from the env

2024-11-28 10:07 UTC, gihansdp approved these changes

2024-11-28 10:08 UTC, merged